# Generated by Django 5.2.6 on 2025-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('balls', 'Balls')], default='update', max_length=20),
        ),
    ]
